### ISSUE TITLE
iPhone 14 pro max iOS 16.5 doesn’t work 

### ISSUE THREAD

**Issue by themexriver041** [RUGMJ/pinnacle#11]
Hello,
your tweak doesn’t work. I'm using an iPhone 14 Pro Max with iOS 16.5. Could you please address the problem? Thank you.

**Comment by RUGMJ** [comment]
What do you mean it doesn't work? Does it crash? Send a crash log

**Comment by themexriver041** [comment]
After being installed, it shows no signs of functionality.

**Comment by themexriver041** [comment]
![image](https://github.com/RUGMJ/pinnacle/assets/164617752/366bb9c4-9d83-4733-9d2f-535dc7b6f787)

**Comment by RUGMJ** [comment]
- To create a stack enter wiggle mode and swipe up on the app you want to add the stack to. Then tap any of the + icons and choose the app to add.
- To expand the stack just swipe up on the app of the stack you want to expand.
- To remove an app from a stack enter wiggle mode, expand the stack you want to remove an app from, tap on the app you wish to remove and press the remove button in the top right.
- All animations are fully customizable via the settings menu

**Comment by themexriver041** [comment]
Thanks, I'll check it out.
