### ISSUE TITLE
[BUG] Apps in stacks create duplicate icons

### ISSUE THREAD

**Issue by MrTeed** [RUGMJ/pinnacle#14]
When you add an app to a stack the app you added also stays out of the stack.

Example. Add mail to messages stack, mail will appear in stack and outside of stack.

You can see the size of the mail icon. It's in the stack while it's slightly smaller, and still on the home screen full sized. When you open the stack the duplicate disappears but as you swap between screens it comes back.

iPhone 14 iOS 16.4 

![20240324_015928604_iOS](https://github.com/RUGMJ/pinnacle/assets/115820386/9682f9a5-7e19-4ae1-a47e-5fac3bbd3d48)
![20240324_015937004_iOS](https://github.com/RUGMJ/pinnacle/assets/115820386/43a26421-0939-4b26-ad2e-fe29c88f9e5e)

**Comment by RUGMJ** [comment]
I cant seem to reproduce this, could you go into more detail on how you came across this behaviour?

**Comment by RUGMJ** [comment]
OP sent a video on discord, isnt a critical bug and doesnt prevent the use of the tweak
