### ISSUE TITLE
Was stupid and didn’t read

### ISSUE THREAD

**Issue by zeiss01** [RUGMJ/pinnacle#15]
I clicked on this tweak super excited it was just like apex and loved that tweak! Went ahead and bought the tweak and won’t let me install, further investigation realized it’s for iOS 16 and I’m on 15.1.1 and cannot upgrade to iOS 16 to enjoy this tweak would appreciate a refund due to my lack of reading

**Comment by RUGMJ** [comment]
Sure send me an email at rugmjtweakdev@gmai.com with your order number :)
