### ISSUE TITLE
[Bug] After the folder is opened, it will be logged out.

### ISSUE THREAD

**Issue by yaoylong** [RUGMJ/pinnacle#20]
ip14pm 16.5

In the file, slide to open it, click back, and you must log out.

在文件中滑动打开，然后不点app，返回退回桌面，一定会注销，次次都会。

**Comment by RUGMJ** [comment]
I'm sorry I dont understand what you mean, could you send a video or pictures with the bug occurring?

**Comment by Jenzilly** [comment]
I’m pretty sure he means this. 

While inside a folder, while you’re in wiggle mode and you slide up on an app to add to the stack and then you slide up on the home bar, this causes a respring. Basically, you have to tap somewhere on the screen to exit the stack edit mode, or else you’ll respring if you leave stack edit mode by swiping up on the home bar and attempt to enter the folder again. 

happens to me on iphone 14 pro 16.2

**Comment by Jenzilly** [comment]
Just had a respring after i swiped up on the home bar while i was inside a stack inside of a folder so i guess you dont need to be in edit mode.

**Comment by RUGMJ** [comment]
I cant reproduce this
