### ISSUE TITLE
[BUG] Apps do not move out of the way of the stack

### ISSUE THREAD

**Issue by ProvokedGamer** [RUGMJ/pinnacle#23]
**Describe the bug**
The surrounding apps get merged with the apps in the stack.

**To Reproduce**
1. Go to a page on the home screen with at least one stack on it.
2. Close/lock your phone and immediately open it again.
3. Open a stack on that page immediately.
4. The other apps do not move out of the way of the stack.

**Expected behavior**
The stack would open and the other apps would be pushed out of the way. Instead, they sorta fuse with the stack.

**Screenshots**
![image](https://github.com/RUGMJ/pinnacle/assets/119907145/5ce569ab-d08b-414f-ab7f-00ffc337fcfd)![image](https://github.com/RUGMJ/pinnacle/assets/119907145/51cc8dd7-af44-4a11-8186-34c18c35d3d3)

**Smartphone:**
 - Device: [iPhone 8+]
 - IOS Version [iOS 15.6]

**Additional context**
The bug does not happen if you have your phone on a page on the home screen that does not have any stacks in it, and then swipe to a page that does and open the stack.

**Comment by RUGMJ** [comment]
This is very strange as I cannot reproduce this, my guess is its something thats different between ios 15 and ios 16, if you want a refund email me at rugmjtweakdev@gmail.com
