### ISSUE TITLE
[BUG] Safemode on Home Button Press

### ISSUE THREAD

**Issue by ProvokedGamer** [RUGMJ/pinnacle#34]
**Describe the bug**
Pressing the home button while a Pinnacle stack is open causes springboard to crash.

**To Reproduce**
1. Go to any page on the Home Screen that isn’t the first page
2. Swipe and open a Pinnacle stack
3. Press the home button
4. You should be directed to the first page, then the springboard should crash.

**Expected behavior**
Springboard not crashing

**Screenshots**
N/A

**Smartphone:**
 - Device: iPhone 8+
 - IOS Version 15.6

**Additional context**
There are crash logs I got from crashing:
https://pastebin.com/d4QrYjVQ

**Comment by RUGMJ** [comment]
Cant reproduce
