### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RadioBlackbird** [RUGMJ/pinnacle#36]
**Describe the bug**
The phone reboots into safe mode whenever I press the home button if I've activated the swipe up gesture.

**To Reproduce**
1. Swipe up on an app that has nested apps
2. Press home button

**Expected behavior**
Expect phone to scroll back to Home Screen.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - IOS Version 15.3.1

**Comment by RUGMJ** [comment]
Cant reproduce
