### ISSUE TITLE
[FEAT] Question about functionality 

### ISSUE THREAD

**Issue by gititwhileyoucan** [RUGMJ/pinnacle#37]
**Is your feature request related to a problem? Please describe.**

No problem, just a question. 

Having just learned about your tweak, Pinnacle, I’d like to know is swiping down is an option. I was a long time user of Apex and Zenith, and am quite used to that method. 

Thank you.

**Comment by Janisbtw** [comment]
Check out the Pinnacle settings where you can change the gesture from up to down

**Comment by gititwhileyoucan** [comment]
Thank you. It’s just that I haven't purchased it yet and therefore can't see settings. But you indicate up and/or down works, so that's good!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gititwhileyoucan** [comment]
Sorry, I’m not too good at GitHub. 
I purchased and installed Pinnacle on my Xr iOS 15.1 with Dopamine 2. I previously used Zenith but uninstalled it. Pinnacle will not work. I have resprung, run ICleaner, reinstalled Pinnacle (and the two support files it installs), rebooted and rejailbroke, but sill no luck. When I swipe up or down on an app, nothing happens. Can you please advise? 
Thank you.

**Comment by gititwhileyoucan** [comment]
Sorry, I’m not too good at GitHub.

Yesterday I purchased and installed Pinnacle on my Xr iOS 15.1 with Dopamine 2. I previously used Zenith but uninstalled it. Pinnacle will not work. I have resprung, run ICleaner, reinstalled Pinnacle (and the two support files it installs), rebooted and rejailbroke, but still no luck. When I swipe up or down on an app, nothing happens. Can you please advise?
Thank you.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
