### ISSUE TITLE
[BUG] Not activating

### ISSUE THREAD

**Issue by gititwhileyoucan** [RUGMJ/pinnacle#38]
Hello. I have just purchased and installed Pinnacle on my Xr, iOS 15.1 and Dopamine 2. I previously had Zenith working and uninstalled it. But Pinnacle
doesn’t seem to work. No swipe up or down causes stack buttons to appear. I reinstalled Pinnacle, ran ICleaner and resprung, but no difference. Can you please advise?

**Comment by RUGMJ** [comment]
Are you sure you're using the tweak correctly? Re-read the depiction, my guess is that you're not in 'wiggle mode' when you're trying to edit the stack
