### ISSUE TITLE
[BUG] Slight incompatibility with PrimalFolder 2

### ISSUE THREAD

**Issue by DDjusD** [RUGMJ/pinnacle#40]
**Describe the bug**
When both tweaks are installed the “Tap to Close” feature of PrimalFolder 2 stops working. This feature is super useful when using a tweak to make folders bigger as it allows you to close folder by tapping on an empty spot of the background.

**To Reproduce**
1. Install both tweaks
2. Enable “Tap to Close” in PrimalFolder 2’s settings3. 
3. Attempt to close an open folder by tapping on the folder background

**Expected behavior**
The folder should close when tapping on the background of the folder with “Tap to Close” enabled in 
PrimalFolder 2’s settings, however this tweak stops it from working properly.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13] iPhone 13 Pro Max
 - IOS Version [e.g. 16.1] 15.4.1

**Additional context**
I know it’s not a huge issue, but it is an issue that would be nice to have fixed for the minority of us that use the two tweaks. Especially so for me as I also use Bolders Reborn to make folders bigger (they take up the whole screen) and without this feature the only way I have to close folders is to swipe up from the bottom of the screen which can be pretty inconvenient.

**Comment by RUGMJ** [comment]
For some stupid reason although primal folders 2 is free its not open source which means fixing this would be stupidly hard, so its not really worth the effort to fix, if you can get the dev to share the source code i'd be happy to have a look at this or if you want a refund for pinnacle you can email rugmjtweakdev@gmail.com
