### ISSUE TITLE
[BUG] Tweak doesn’t function at all

### ISSUE THREAD

**Issue by Naderismyname** [RUGMJ/pinnacle#41]
I purchased this tweak and it doesn’t work on my iPhone 14 Pro Max iOS 16.5 I tried putting it in wiggle mode and swipe up but that doesn’t do anything please help me

**Comment by RUGMJ** [comment]
Sorry I haven't responded sooner, would you be able to supply a screen recording of the issue?

**Comment by Naderismyname** [comment]
Hello,

There is nothing to record, it doesn’t work whatsoever maybe you could send
me a guide on how to use it?

**Comment by RUGMJ** [comment]
Read the depiction on the havoc page

**Comment by Naderismyname** [comment]
What does it say?

**Comment by RUGMJ** [comment]
https://havoc.app/package/pinnacle

**Comment by Naderismyname** [comment]
There’s no error code it’s just not functional whatsoever
