### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by jcmcrack** [RUGMJ/pinnacle#43]
**Is your feature request related to a problem? Please describe.**
I tried to use it in an iPhone 13 16.1.1 is very buggy, can’t use it in the dock? 
I want the refund, thanks
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RUGMJ** [comment]
Dock support isn't currently supported (#1), if you'd like a refund email tweakdev@rugmj.dev
