### ISSUE TITLE
[BUG]always safe model

### ISSUE THREAD

**Issue by gxmidy** [RUGMJ/pinnacle#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13]
 - IOS Version [e.g. 16.1]

**Additional context**

**Comment by RUGMJ** [comment]
Could you fill out the issue format please? I need to be able to recreate this in order to fix it

**Comment by RUGMJ** [comment]
Closing as theres nothing i can do without more information
