### ISSUE TITLE
[BUG] Usage in dock causes bugginess

### ISSUE THREAD

**Issue by GZTY959** [RUGMJ/pinnacle#6]
The problem I discovered 
![194E1202-21C4-4E4F-A429-42B261BEDFD6](https://github.com/RUGMJ/pinnacle/assets/132641421/659be480-fe20-40c1-9e1b-dc9d90dc254d)
⚠️If used in the dock section, it will cause the phone to be unresponsive

**Comment by GZTY959** [comment]
Sorry, I don't know how to provide feedback on this bug. You just need to look at the picture and the paragraph below it

**Comment by RUGMJ** [comment]
The tweak isn't meant to be used in the dock atm, I have code which tries to prevent it working there but obviously thats not working correctly. If you'd like a refund send me an email :)

**Comment by GZTY959** [comment]
我喜欢这个插件，不会退款，我想提个建议，后续是否会增加到在dock上工作呢？我觉得在dock上工作会

**Comment by GZTY959** [comment]
I like this plugin and there will be no refund. I would like to make a suggestion, will it be added to working on the dock in the future? I think working on a dock would be cool. Even if not, it's just a little regret.

**Comment by RUGMJ** [comment]
Yes dock support is planned see #1

**Comment by GZTY959** [comment]
Wow, okay.

**Comment by RUGMJ** [comment]
What device and version were you using here? I cant seem to reproduce it

**Comment by GZTY959** [comment]
iPhone14Pro Max，iOS16.3.1。Please try following the first 12 seconds of operation. There will be no response for the next minute. Then automatically restart SpringBoard. I accelerated the process in the middle.

Uploading IMG_4126.MOV…

**Comment by Janisbtw** [comment]
> iPhone14Pro Max，iOS16.3.1。Please try following the first 12 seconds of operation. There will be no response for the next minute. Then automatically restart SpringBoard. I accelerated the process in the middle.
> 
> 
> 
> Uploading IMG_4126.MOV…
> 
> 
> 
> 

Your video seems to have been lost

**Comment by GZTY959** [comment]
https://github.com/RUGMJ/pinnacle/assets/132641421/85914873-2f81-4ee2-9e2e-3810187b8fd3

**Comment by RUGMJ** [comment]
yes this is the "expected" behaviour when the check i added isn't there so that's clearly broken for you

**Comment by GZTY959** [comment]
Okay, then
